/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicStreamRouteImport } from './routes/api/public/stream'
import { Route as ApiPublicIngestRouteImport } from './routes/api/public/ingest'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStreamRoute = ApiPublicStreamRouteImport.update({
  id: '/api/public/stream',
  path: '/api/public/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIngestRoute = ApiPublicIngestRouteImport.update({
  id: '/api/public/ingest',
  path: '/api/public/ingest',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/api/public/ingest': typeof ApiPublicIngestRoute
  '/api/public/stream': typeof ApiPublicStreamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/api/public/ingest': typeof ApiPublicIngestRoute
  '/api/public/stream': typeof ApiPublicStreamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/api/public/ingest': typeof ApiPublicIngestRoute
  '/api/public/stream': typeof ApiPublicStreamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/api/public/ingest' | '/api/public/stream'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/api/public/ingest' | '/api/public/stream'
  id: '__root__' | '/' | '/auth' | '/api/public/ingest' | '/api/public/stream'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ApiPublicIngestRoute: typeof ApiPublicIngestRoute
  ApiPublicStreamRoute: typeof ApiPublicStreamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stream': {
      id: '/api/public/stream'
      path: '/api/public/stream'
      fullPath: '/api/public/stream'
      preLoaderRoute: typeof ApiPublicStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ingest': {
      id: '/api/public/ingest'
      path: '/api/public/ingest'
      fullPath: '/api/public/ingest'
      preLoaderRoute: typeof ApiPublicIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ApiPublicIngestRoute: ApiPublicIngestRoute,
  ApiPublicStreamRoute: ApiPublicStreamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
